/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_SIMPLE_PB_H_INCLUDED
#define PB_SIMPLE_PB_H_INCLUDED
#include <protobuf/pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MessageInfo_MessageType {
    MessageInfo_MessageType_OilTankMonitorType = 0,
    MessageInfo_MessageType_ReOilGasType = 1,
    MessageInfo_MessageType_SettingDataType = 2
} MessageInfo_MessageType;

/* Struct definitions */
typedef struct _OilTankMonitor {
    char StationID[16];
    char DateTime[16];
    int32_t DataType;
    int32_t SensorNum;
    int32_t SensorType;
    int32_t SensorSta;
    float SensorDate;
} OilTankMonitor;

typedef struct _ReOilGas {
    char StationID[16];
    char DateTime[16];
} ReOilGas;

typedef struct _SettingData {
    char StationID[16];
    char DateTime[16];
    int32_t OilTankNum;
    int32_t OilTankType;
    int32_t PipeNum;
    int32_t DispenerNum;
    int32_t BasinNum;
    int32_t AmountDispenerNum;
    char GunNum1[32];
    char GunNum2[32];
    char GunNum3[32];
    char GunNum4[32];
    char GunNum5[32];
    char GunNum6[32];
    char GunNum7[32];
    char GunNum8[32];
    char GunNum9[32];
    char GunNum10[32];
    char GunNum11[32];
    char GunNum12[32];
    int32_t PipPreEn;
    int32_t TankPreEN;
    int32_t HclFgaEn;
    int32_t FgaNum;
    int32_t RadarEn;
    int32_t CrashNum;
    int32_t Reserve1;
    int32_t Reserve2;
    int32_t Reserve3;
} SettingData;

typedef struct _MessageInfo {
    MessageInfo_MessageType message_tpye;
    pb_size_t which_messageBody;
    union {
        OilTankMonitor oilTankMonitor;
        ReOilGas reOilGas;
        SettingData settingData;
    } messageBody;
} MessageInfo;


/* Helper constants for enums */
#define _MessageInfo_MessageType_MIN MessageInfo_MessageType_OilTankMonitorType
#define _MessageInfo_MessageType_MAX MessageInfo_MessageType_SettingDataType
#define _MessageInfo_MessageType_ARRAYSIZE ((MessageInfo_MessageType)(MessageInfo_MessageType_SettingDataType+1))


/* Initializer values for message structs */
#define MessageInfo_init_default                 {_MessageInfo_MessageType_MIN, 0, {OilTankMonitor_init_default}}
#define OilTankMonitor_init_default              {"", "", 0, 0, 0, 0, 0}
#define ReOilGas_init_default                    {"", ""}
#define SettingData_init_default                 {"", "", 0, 0, 0, 0, 0, 0, "", "", "", "", "", "", "", "", "", "", "", "", 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MessageInfo_init_zero                    {_MessageInfo_MessageType_MIN, 0, {OilTankMonitor_init_zero}}
#define OilTankMonitor_init_zero                 {"", "", 0, 0, 0, 0, 0}
#define ReOilGas_init_zero                       {"", ""}
#define SettingData_init_zero                    {"", "", 0, 0, 0, 0, 0, 0, "", "", "", "", "", "", "", "", "", "", "", "", 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define OilTankMonitor_StationID_tag             1
#define OilTankMonitor_DateTime_tag              2
#define OilTankMonitor_DataType_tag              3
#define OilTankMonitor_SensorNum_tag             4
#define OilTankMonitor_SensorType_tag            5
#define OilTankMonitor_SensorSta_tag             6
#define OilTankMonitor_SensorDate_tag            7
#define ReOilGas_StationID_tag                   1
#define ReOilGas_DateTime_tag                    2
#define SettingData_StationID_tag                1
#define SettingData_DateTime_tag                 2
#define SettingData_OilTankNum_tag               3
#define SettingData_OilTankType_tag              4
#define SettingData_PipeNum_tag                  5
#define SettingData_DispenerNum_tag              6
#define SettingData_BasinNum_tag                 7
#define SettingData_AmountDispenerNum_tag        8
#define SettingData_GunNum1_tag                  9
#define SettingData_GunNum2_tag                  10
#define SettingData_GunNum3_tag                  11
#define SettingData_GunNum4_tag                  12
#define SettingData_GunNum5_tag                  13
#define SettingData_GunNum6_tag                  14
#define SettingData_GunNum7_tag                  15
#define SettingData_GunNum8_tag                  16
#define SettingData_GunNum9_tag                  17
#define SettingData_GunNum10_tag                 18
#define SettingData_GunNum11_tag                 19
#define SettingData_GunNum12_tag                 20
#define SettingData_PipPreEn_tag                 21
#define SettingData_TankPreEN_tag                22
#define SettingData_HclFgaEn_tag                 23
#define SettingData_FgaNum_tag                   24
#define SettingData_RadarEn_tag                  25
#define SettingData_CrashNum_tag                 26
#define SettingData_Reserve1_tag                 27
#define SettingData_Reserve2_tag                 28
#define SettingData_Reserve3_tag                 29
#define MessageInfo_oilTankMonitor_tag           2
#define MessageInfo_reOilGas_tag                 3
#define MessageInfo_settingData_tag              4
#define MessageInfo_message_tpye_tag             1

/* Struct field encoding specification for nanopb */
#define MessageInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    message_tpye,      1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (messageBody,oilTankMonitor,messageBody.oilTankMonitor),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (messageBody,reOilGas,messageBody.reOilGas),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (messageBody,settingData,messageBody.settingData),   4)
#define MessageInfo_CALLBACK NULL
#define MessageInfo_DEFAULT NULL
#define MessageInfo_messageBody_oilTankMonitor_MSGTYPE OilTankMonitor
#define MessageInfo_messageBody_reOilGas_MSGTYPE ReOilGas
#define MessageInfo_messageBody_settingData_MSGTYPE SettingData

#define OilTankMonitor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   StationID,         1) \
X(a, STATIC,   SINGULAR, STRING,   DateTime,          2) \
X(a, STATIC,   SINGULAR, INT32,    DataType,          3) \
X(a, STATIC,   SINGULAR, INT32,    SensorNum,         4) \
X(a, STATIC,   SINGULAR, INT32,    SensorType,        5) \
X(a, STATIC,   SINGULAR, INT32,    SensorSta,         6) \
X(a, STATIC,   SINGULAR, FLOAT,    SensorDate,        7)
#define OilTankMonitor_CALLBACK NULL
#define OilTankMonitor_DEFAULT NULL

#define ReOilGas_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   StationID,         1) \
X(a, STATIC,   SINGULAR, STRING,   DateTime,          2)
#define ReOilGas_CALLBACK NULL
#define ReOilGas_DEFAULT NULL

#define SettingData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   StationID,         1) \
X(a, STATIC,   SINGULAR, STRING,   DateTime,          2) \
X(a, STATIC,   SINGULAR, INT32,    OilTankNum,        3) \
X(a, STATIC,   SINGULAR, INT32,    OilTankType,       4) \
X(a, STATIC,   SINGULAR, INT32,    PipeNum,           5) \
X(a, STATIC,   SINGULAR, INT32,    DispenerNum,       6) \
X(a, STATIC,   SINGULAR, INT32,    BasinNum,          7) \
X(a, STATIC,   SINGULAR, INT32,    AmountDispenerNum,   8) \
X(a, STATIC,   SINGULAR, STRING,   GunNum1,           9) \
X(a, STATIC,   SINGULAR, STRING,   GunNum2,          10) \
X(a, STATIC,   SINGULAR, STRING,   GunNum3,          11) \
X(a, STATIC,   SINGULAR, STRING,   GunNum4,          12) \
X(a, STATIC,   SINGULAR, STRING,   GunNum5,          13) \
X(a, STATIC,   SINGULAR, STRING,   GunNum6,          14) \
X(a, STATIC,   SINGULAR, STRING,   GunNum7,          15) \
X(a, STATIC,   SINGULAR, STRING,   GunNum8,          16) \
X(a, STATIC,   SINGULAR, STRING,   GunNum9,          17) \
X(a, STATIC,   SINGULAR, STRING,   GunNum10,         18) \
X(a, STATIC,   SINGULAR, STRING,   GunNum11,         19) \
X(a, STATIC,   SINGULAR, STRING,   GunNum12,         20) \
X(a, STATIC,   SINGULAR, INT32,    PipPreEn,         21) \
X(a, STATIC,   SINGULAR, INT32,    TankPreEN,        22) \
X(a, STATIC,   SINGULAR, INT32,    HclFgaEn,         23) \
X(a, STATIC,   SINGULAR, INT32,    FgaNum,           24) \
X(a, STATIC,   SINGULAR, INT32,    RadarEn,          25) \
X(a, STATIC,   SINGULAR, INT32,    CrashNum,         26) \
X(a, STATIC,   SINGULAR, INT32,    Reserve1,         27) \
X(a, STATIC,   SINGULAR, INT32,    Reserve2,         28) \
X(a, STATIC,   SINGULAR, INT32,    Reserve3,         29)
#define SettingData_CALLBACK NULL
#define SettingData_DEFAULT NULL

extern const pb_msgdesc_t MessageInfo_msg;
extern const pb_msgdesc_t OilTankMonitor_msg;
extern const pb_msgdesc_t ReOilGas_msg;
extern const pb_msgdesc_t SettingData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MessageInfo_fields &MessageInfo_msg
#define OilTankMonitor_fields &OilTankMonitor_msg
#define ReOilGas_fields &ReOilGas_msg
#define SettingData_fields &SettingData_msg

/* Maximum encoded size of messages (where known) */
#define MessageInfo_size                         614
#define OilTankMonitor_size                      83
#define ReOilGas_size                            34
#define SettingData_size                         609

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
