/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.1 */

#include "xielou.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MessageInfo, MessageInfo, 2)


PB_BIND(OilTankMonitor, OilTankMonitor, AUTO)


PB_BIND(ReOilGas, ReOilGas, AUTO)


PB_BIND(SettingData, SettingData, 2)




